### ISSUE TITLE
image cache files corruption - long term - eliminate issue

### ISSUE THREAD

**Issue by kaisersozeh** [einsteinx2/wiiflow-lite-einstein-mod#2]
Wiiflow will occasionally corrupt an image cache file - the issue is long standing and may have further detail provided on wiiflow - mod and wiiflow - lite repositories.

**Comment by einsteinx2** [comment]
Same comments as #3

**Comment by einsteinx2** [comment]
Closing this in favor of #3 as they both require me to reproduce it, and if I can finally reproduce it I'll just fix it rather than work around it.
